### ISSUE TITLE
Missing SystemRequirements line

### ISSUE THREAD

**Issue by dsteuer** [r-spatial/s2#132]
Hi, would you mind to add a SystemRequirements line to your DESCRIPTION? s2 needs openssl, at least that's the
point where compilation fails. I'm providing R package binaries for openSUSE and depend on as much information as possible
for these external dependencies. (see https://build.opensuse.org/package/show/devel:languages:R:autoCRAN if you are interested) 
Detlef

**Comment by edzer** [comment]
See https://github.com/r-spatial/s2/commit/c87c10db28887ebc7774d46bf1f0b81a5d743f25
