### ISSUE TITLE
unable to load shared object s2.so(Linux centos7 redhat)

### ISSUE THREAD

**Issue by ScrtH** [r-spatial/s2#244]
I install s2 in R, but I still receive error:
unable to load shared object '/usr/local/lib64/R/library/00LOCK-s2/00new/s2/libs/s2.so'
undefined symbol:_ZTVN10_cxxabiv117_class_type_infoE
error:Loading failed
Thanks for your help~

**Comment by ScrtH** [comment]
I have already solved this issue which has been plagued me for a week! I install devtoolset8 and update gcc g++ from 4.8.5 to 8.3.1. And then, I make a mistake when established soft connection about gcc and g++. Specifically, gcc and g++ all connected with gcc, so unable to compile and install R packages using g++.

**Comment by edzer** [comment]
Thanks for reporting!
