### ISSUE TITLE
Installation fails on latest Alpine 3.19.0

### ISSUE THREAD

**Issue by bastistician** [r-spatial/s2#251]
```
In file included from absl/base/internal/low_level_alloc.cc:26:
../src/absl/base/internal/direct_mmap.h:75:25: error: 'off64_t' has not been declared
   75 |                         off64_t offset) noexcept {
      |                         ^~~~~~~
```

See https://github.com/abseil/abseil-cpp/issues/1473 for the corresponding upstream issue.

This can be fixed by porting Commit https://github.com/abseil/abseil-cpp/commit/4500c2fada4e952037c59bd65e8be1ba0b29f21e from upstream. I have confirmed that **s2** 1.1.4 installs and checks successfully on Alpine 3.19.0 if that patch is applied.

**Comment by edzer** [comment]
I need to upload a new version to CRAN Today or tomorrow; is this something you'd want to work in, @paleolimbot, or shall I, or do you want to wait?

**Comment by edzer** [comment]
Thanks, now submitted.

**Comment by edzer** [comment]
On CRAN now!

**Comment by bastistician** [comment]
That was quick. Thank you!
